# This action is hidden from the GitHub Actions UI
name: 'Build Qubership GCIP Docker Image'
description: 'Build and push Qubership GCIP docker image to container registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Docker image name'
    required: false
    default: 'qubership-gcip'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './build_gcip/build/Dockerfile'
  git-user:
    description: 'Git username for build args'
    required: false
  git-token:
    description: 'Git token for build args'
    required: false
  github-token:
    description: 'GitHub token for registry login'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Generate custom tags with timestamp
      id: tags
      shell: bash
      run: |
        # Get current branch name and convert slashes to dashes
        BRANCH_NAME="${{ github.ref_name }}"
        DOCKER_TAG=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
        
        # Generate timestamp in format YYYYMMDD-HHMMSS
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        
        # Create custom tag: branch_timestamp
        CUSTOM_TAG="${DOCKER_TAG}_${TIMESTAMP}"
        
        # Create branch-latest tag for the current branch
        BRANCH_LATEST_TAG="${DOCKER_TAG}-latest"
        
        echo "Branch: $BRANCH_NAME"
        echo "Docker tag: $DOCKER_TAG"
        echo "Timestamp: $TIMESTAMP"
        echo "Custom tag: $CUSTOM_TAG"
        echo "Branch latest tag: $BRANCH_LATEST_TAG"
        
        # Set output for next steps
        echo "custom_tag=$CUSTOM_TAG" >> $GITHUB_OUTPUT
        echo "branch_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "branch_latest_tag=$BRANCH_LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository_owner | lower }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-{{sha}},suffix={{timestamp}}
          type=raw,value={{branch}}_{{timestamp}}
    
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ github.repository_owner | lower }}/${{ inputs.image-name }}:${{ steps.tags.outputs.custom_tag }}
          ${{ inputs.registry }}/${{ github.repository_owner | lower }}/${{ inputs.image-name }}:${{ steps.tags.outputs.branch_latest_tag }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_USER=${{ inputs.git-user }}
          GIT_TOKEN=${{ inputs.git-token }} 