name: "Dev: Build Qubership EnvGene docker images"

run-name: "Build EnvGene docker images for commit ${{ github.sha }}"

on:
  workflow_dispatch:
    inputs:
      build-gcip:
        description: 'Build Qubership GCIP image'
        required: false
        default: true
        type: boolean
      build-envgene:
        description: 'Build Qubership Envgene image'
        required: false
        default: true
        type: boolean
      build-effective-set:
        description: 'Build Effective Set Generator image'
        required: false
        default: true
        type: boolean
      build-effective-set-python:
        description: 'Build Effective Set Generator Python image'
        required: false
        default: true
        type: boolean
      build-pipeline:
        description: 'Build Instance Repo Pipeline image'
        required: false
        default: true
        type: boolean  
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'

env:
  REGISTRY: ghcr.io
  CI_PROJECT_DIR: ${{ github.workspace }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  tests:
    if: |
      github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim-bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
      
      - name: Run Tests
        uses: ./.github/actions/run-tests

  build-qubership-gcip:
    needs: [tests]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-gcip == 'true') || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Qubership GCIP Docker Image
        uses: ./.github/actions/build-gcip
        with:
          registry: ${{ env.REGISTRY }}
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-qubership-envgene:
    needs: [tests]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-envgene == 'true') || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Qubership Envgene Docker Image
        uses: ./.github/actions/build-envgene
        with:
          registry: ${{ env.REGISTRY }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-effective-set-jar:
    needs: [tests]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-effective-set == 'true') || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode package -Dgpg.skip=true -f build_effective_set_generator_java/pom.xml"
      java-version: 17
      upload-artifact: true
      artifact-id: effective_set_jar
      ref: ${{ github.ref }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}

  build-effective-set-generator:
    needs: [build-effective-set-jar]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-effective-set == 'true') || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Effective Set Generator Docker Image
        uses: ./.github/actions/build-effective-set
        with:
          registry: ${{ env.REGISTRY }}
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-effective-set-generator-python:
    needs: [tests]
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.build-effective-set-python == 'true') || (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Effective Set Generator Python Docker Image
        uses: ./.github/actions/build-effective-set-python
        with:
          registry: ${{ env.REGISTRY }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-instance-repo-pipeline:
    needs: 
      - tests
      - build-qubership-gcip
      - build-qubership-envgene
      - build-effective-set-generator
      - build-effective-set-generator-python
    if: |
      always() && 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.build-pipeline == 'true') || 
      (github.event_name == 'push' && (contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'BREAKING CHANGE')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Image Tags in Pipeline
        run: |
          # Get current branch name and convert slashes to dashes for docker tag
          BRANCH_NAME="${{ github.ref_name }}"
          DOCKER_TAG=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
          
          # Generate timestamp in format YYYYMMDD-HHMMSS
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          
          # Create custom tag: branch_timestamp
          CUSTOM_TAG="${DOCKER_TAG}_${TIMESTAMP}"
          
          # Create branch-latest tag for the current branch
          BRANCH_LATEST_TAG="${DOCKER_TAG}"
          
          echo "Current branch: $BRANCH_NAME"
          echo "Docker tag: $DOCKER_TAG"
          echo "Timestamp: $TIMESTAMP"
          echo "Custom tag: $CUSTOM_TAG"
          echo "Branch latest tag: $BRANCH_LATEST_TAG"
          
          # Check which images were built and update accordingly
          if [[ "${{ needs.build-qubership-gcip.result }}" == "success" ]]; then
            echo "Updating qubership-gcip tag to $BRANCH_LATEST_TAG"
            sed -i "s|qubership-gcip:[^'[:space:]]*|qubership-gcip:$BRANCH_LATEST_TAG\'|g" github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
          fi
          
          if [[ "${{ needs.build-qubership-envgene.result }}" == "success" ]]; then
            echo "Updating qubership-envgene tag to $BRANCH_LATEST_TAG"
            sed -i "s|qubership-envgene:[^'[:space:]]*|qubership-envgene:$BRANCH_LATEST_TAG\'|g" github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
          fi
          
          if [[ "${{ needs.build-effective-set-generator.result }}" == "success" ]]; then
            echo "Updating qubership-effective-set-generator tag to $BRANCH_LATEST_TAG"
            sed -i "s|qubership-effective-set-generator:[^'[:space:]]*|qubership-effective-set-generator:$BRANCH_LATEST_TAG\'|g" github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
          fi
          
          if [[ "${{ needs.build-effective-set-generator-python.result }}" == "success" ]]; then
            echo "Updating qubership-effective-set-generator-python tag to $BRANCH_LATEST_TAG"
            sed -i "s|qubership-effective-set-generator-python:[^'[:space:]]*|qubership-effective-set-generator-python:$BRANCH_LATEST_TAG\'|g" github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
          fi
          
          # Check if any images were updated
          if git diff --quiet github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml; then
            echo "No changes to commit - no images were built or tags were already up to date"
          else
            echo "Updated pipeline.yml with docker tag: $BRANCH_LATEST_TAG"
          fi
          
          # Show the changes
          echo "Changes made to pipeline.yml:"
          git diff github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml || true
          
          # Commit the changes only if there are actual changes
          if ! git diff --quiet github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml; then
            git config --global user.name "qubership-actions[bot]"
            git config --global user.email "qubership-actions[bot]@users.noreply.github.com"
            git add github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
            git commit -m "Update docker image tags to $BRANCH_LATEST_TAG for branch $BRANCH_NAME"
            
            # Push the changes
            git push origin HEAD:${{ github.ref_name }} || echo "Failed to push changes"
          else
            echo "No changes to commit - skipping git operations"
          fi

      - name: Build Instance Repo Pipeline Docker Image
        uses: ./.github/actions/build-pipeline
        with:
          registry: ${{ env.REGISTRY }}
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
